### ISSUE TITLE
Reference frame rotation

### ISSUE THREAD

**Issue by poliandre98** [SvenLilge/tdcr-modeling#1]
I want to apply a rotation to the system so that I obtain the continuum robot placed horizontally and the gravity Force acting on Z-axis. I tried multiplying the transformation matrix of each segment by a rotation matrix about Z and X axes but I did not succeed. Can you suggest how to implement that part? 
Thank you

**Comment by priyankarao257** [comment]
Hi,

One approach could be to simply assume that the gravity vector is along the x-axis - this way the system would be horizontal with the z axis parallel to the ground

Another approach could be to apply the transformation after you calculate all the coordinates. This would a rotation about the x axis, followed by rotation about the z axis. Is this what you tried too ? Can you send your transformation matrices so that we can zero-in on the problem?
